DROP TABLE IF EXISTS app_action_log;

CREATE TABLE app_action_log (
  id SERIAL NOT NULL,
  app_id VARCHAR(255) DEFAULT NULL,
  message VARCHAR(255) DEFAULT NULL,
  tag VARCHAR(255) DEFAULT NULL,
  timestamp TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);
