DROP TABLE IF EXISTS `app_action_log`;

CREATE TABLE `app_action_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `app_id` VARCHAR(255) DEFAULT NULL,
  `message` VARCHAR(255) DEFAULT NULL,
  `tag` VARCHAR(255) DEFAULT NULL,
  `timestamp` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
);
